### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by bennyd87708** [71/BeatSinger#10]
mod has been broken a while so I ask: are there any plans to keep it updated or is it abandoned? I really liked this mod

**Comment by 71** [comment]
Oh, I haven't really played BS since the last update so I didn't know it was broken! I'm gonna have a look at it.

**Comment by 71** [comment]
**Update**: Updated for 0.12.2!

**Comment by bennyd87708** [comment]
wow thanks!!

**Comment by jonschtote** [comment]
I think its broken for newest update again and I JUST got vr specifically to use this mod in BS because I already had it for PSVR.

If you could update this mod for 1.1.0p1, I would donate a couple coffee/beers to you.
