### ISSUE TITLE
default songs

### ISSUE THREAD

**Issue by bennyd87708** [71/BeatSinger#12]
Is there any way to use a custom json file for lyrics for a song that came with the game such as POP STARS?

**Comment by 71** [comment]
Nope, custom songs and default songs are represented slightly differently behind the scenes, and BeatSinger only takes care of custom songs. Adding support for default songs shouldn't be too hard though, even if I haven't done it yet.

**Comment by bennyd87708** [comment]
Yeah, I figured they were separate. Thanks
